Repository DeveloperAcademy-POSTECH/MC3-Team17-Hou, pull requests merged in 2022-07, with the labels that each got.

#3 [feature] #2 : add ios App project
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Ninano/Ninano.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Ninano/Ninano/AppDelegate.swift
  Ninano/Ninano/Assets.xcassets/AccentColor.colorset/Contents.json
  Ninano/Ninano/Assets.xcassets/AppIcon.appiconset/Contents.json
  Ninano/Ninano/Assets.xcassets/Contents.json
  Ninano/Ninano/Base.lproj/LaunchScreen.storyboard
  Ninano/Ninano/Base.lproj/Main.storyboard
  Ninano/Ninano/Info.plist
  Ninano/Ninano/Ninano.xcdatamodeld/.xccurrentversion
  Ninano/Ninano/Ninano.xcdatamodeld/Ninano.xcdatamodel/contents
  Ninano/Ninano/SceneDelegate.swift
  Ninano/Ninano/ViewController.swift
Labels: feature

#17 [feat]:#16 가로모드로 안 돌아가게 하기
  Ninano/Ninano.xcodeproj/project.pbxproj
Labels: feat

#21 [feat] #20 add todo in swiftLint
  Ninano/Ninano/.swiftlint.yml
Labels: feat

#18 [feat]: #9 알림뷰(NoticeView) UI 구현
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Assets.xcassets/AppIcon.appiconset/Contents.json
  Ninano/Ninano/Info.plist
  Ninano/Ninano/Notice/InterestListViewController.swift
  Ninano/Ninano/Notice/KeywordTableViewCell.swift
  Ninano/Ninano/Notice/KeywordViewController.swift
  Ninano/Ninano/Notice/LineSegmentedControl.swift
  Ninano/Ninano/Notice/Notice.storyboard
  Ninano/Ninano/Notice/NoticeGridCollectionViewCell.swift
  Ninano/Ninano/Notice/NoticeViewController.swift
Labels: feat

#19 [feat]: #14 달력 View UI 구현
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano.xcodeproj/xcshareddata/xcschemes/Ninano.xcscheme
  Ninano/Ninano/Assets.xcassets/CalendarBackground.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/CalendarBackground.imageset/Image.png
  Ninano/Ninano/Calendar.storyboard
  Ninano/Ninano/CalendarCollectionViewCell.swift
  Ninano/Ninano/CalendarCollectionViewCell.xib
  Ninano/Ninano/CalendarViewController.swift
  Ninano/Ninano/Config.xcconfig
  Ninano/Ninano/Info.plist
Labels: feat

#23 [feat]: #12 공연 및 축제 검색 View UI 구현
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Assets.xcassets/performanceImage1.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/performanceImage1.imageset/performanceImage1.jpeg
  Ninano/Ninano/Assets.xcassets/performanceImage2.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/performanceImage2.imageset/performanceImage2.jpeg
  Ninano/Ninano/Base.lproj/Main.storyboard
  Ninano/Ninano/Info.plist
  Ninano/Ninano/SearchResult/CalenderSearchResultViewController.swift
  Ninano/Ninano/SearchResult/PerformancesViewCell.swift
  Ninano/Ninano/SearchResult/SearchResult.storyboard
  Ninano/Ninano/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/extension/UIColor.swift
Labels: feat, question

#26 [feat] #22 포스터 상세정보 View Ui 구현
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Ninano/Ninano/Assets.xcassets/22000743_p.imageset/22000743_p.png
  Ninano/Ninano/Assets.xcassets/22000743_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22005098_p.imageset/22005098_p.png
  Ninano/Ninano/Assets.xcassets/22005098_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22005101_p.imageset/22005101_p.png
  Ninano/Ninano/Assets.xcassets/22005101_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22005605_p.imageset/22005605_p.png
  Ninano/Ninano/Assets.xcassets/22005605_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22006547_p.imageset/22006547_p.png
  Ninano/Ninano/Assets.xcassets/22006547_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22006827_p.imageset/22006827_p.png
  Ninano/Ninano/Assets.xcassets/22006827_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22007535_p.imageset/22007535_p.png
  Ninano/Ninano/Assets.xcassets/22007535_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22007929_p.imageset/22007929_p.png
  Ninano/Ninano/Assets.xcassets/22007929_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22008595_p.imageset/22008595_p.png
  Ninano/Ninano/Assets.xcassets/22008595_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22008615_p.imageset/22008615_p.png
  Ninano/Ninano/Assets.xcassets/22008615_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22008683_p.imageset/22008683_p.png
  Ninano/Ninano/Assets.xcassets/22008683_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/P0003009_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/P0003009_p.imageset/P0003009_p.png
  Ninano/Ninano/Assets.xcassets/Poster/Contents.json
  Ninano/Ninano/Base.lproj/Main.storyboard
  Ninano/Ninano/DetailLinkViewController.swift
  Ninano/Ninano/ModalCalendarViewController.swift
  Ninano/Ninano/SetKeywordViewController.swift
  Ninano/Ninano/ViewController.swift
Labels: feat

#29 [feat]: #28 SearchResult 뷰에서 키워드 알림 UI 구현
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Ninano/Ninano.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Ninano/Ninano/Controllers/EventTab/SearchResultViewController.swift
  Ninano/Ninano/Storyboard/SearchResult.storyboard
  Ninano/Ninano/extension/Label+padding.swift
Labels: feat

#31 [Fix] #30 공연 추천 View PR #25 잔여 코멘트 반영
  Ninano/Ninano/Controllers/EventTab/SearchViewController.swift
  Ninano/Ninano/Storyboard/Search.storyboard
  Ninano/Ninano/Views/CalendarTab/CategoryCell.swift
Labels: fix

#27 [Feat] #15 달력 상세 View UI 구현
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Assets.xcassets/CalendarDetail/Contents.json
  Ninano/Ninano/Assets.xcassets/CalendarDetail/JulyBG.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/CalendarDetail/JulyBG.imageset/JulyBG.png
  Ninano/Ninano/Assets.xcassets/CalendarDetail/banhyang.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/CalendarDetail/banhyang.imageset/banhyang.png
  Ninano/Ninano/Assets.xcassets/CalendarDetail/guiTo.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/CalendarDetail/guiTo.imageset/guiTo.png
  Ninano/Ninano/Controllers/CalendarTab/Calendar/CalendarDetailViewController.swift
  Ninano/Ninano/Storyboard/CalendarDetail.storyboard
  Ninano/Ninano/Views/CalendarTab/DayEventDetailCell.swift
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendarCell.swift
Labels: feat

#39 [feat] 달력에서 날짜 선택시 button에 날짜 기록됨
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Controllers/EventTab/CalenderSearchResultViewController.swift
  Ninano/Ninano/Controllers/EventTab/SearchResultViewController.swift
  Ninano/Ninano/Storyboard/SearchResult.storyboard
  Ninano/Ninano/extension/DateFormatter.swift
Labels: feat, question

#42 [feat]: #34 API 파싱할 모델 및 매니저 추가하기
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/APICaller.swift
  Ninano/Ninano/Controllers/CalendarTab/Calendar/CalendarViewController.swift
  Ninano/Ninano/Controllers/EventTab/EventDetailViewController.swift
  Ninano/Ninano/Info.plist
  Ninano/Ninano/Model.swift
  Ninano/Ninano/Test.storyboard
  Ninano/Ninano/TestTableViewCell.swift
  Ninano/Ninano/TestViewController.swift
Labels: feat

#47 [feat] #46 PosterDetailView Ui 수정
  Ninano/Ninano/Controllers/CalendarTab/Interest/SetKeywordViewController.swift
  Ninano/Ninano/Controllers/EventDetail/EventDetailViewController.swift
  Ninano/Ninano/Controllers/EventDetail/ModalCalendarViewController.swift
  Ninano/Ninano/Storyboard/EventDetailViewCell.xib
  Ninano/Ninano/Views/Base.lproj/EventDetail.storyboard
Labels: feat, fix

#54 [fix]: #53 SearchResultView heartUI 제거
  Ninano/Ninano/Views/EventTab/SerchResult/PerformancesViewCell.swift
  Ninano/Ninano/Views/EventTab/SerchResult/SearchResult.storyboard
Labels: fix

#57 [refact] SearchResultView View 분리
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/APITest/APICaller.swift
  Ninano/Ninano/APITest/Model.swift
  Ninano/Ninano/CalenderModalViewController.swift
  Ninano/Ninano/Controllers/CalendarTab/MonthlyCalendar/CalendarViewController.swift
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Views/CalenderModal.storyboard
  Ninano/Ninano/Views/EventTab/SerchResult/EventFilterButton.swift
  Ninano/Ninano/Views/EventTab/SerchResult/EventFilterButton.xib
  Ninano/Ninano/Views/EventTab/SerchResult/SearchResult.storyboard
  Ninano/Ninano/extension/customDesign/LabelPadding.swift
Labels: refactor

#59 [feat] #58 add color extention
  Ninano/Ninano/extension/UIColor.swift
Labels: feat

#48 [Feat] #38 공연 추천 뷰 API에서 불러온 데이터로 포스터 이미지 표시
  Ninano/Ninano/APITest/APICaller.swift
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendar/CategoryCell.swift
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendar/EventCell.swift
  Ninano/Ninano/Views/EventTab/Search/Search.storyboard
Labels: feat

#55 [feat] CoreData 추가
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Controllers/CalendarTab/Interest/NoticeViewController.swift
  Ninano/Ninano/Controllers/CalenderModalViewController.swift
  Ninano/Ninano/CoreData/KeywordManager.swift
  Ninano/Ninano/CoreData/LikeManager.swift
  Ninano/Ninano/CoreData/NinanoModel.xcdatamodeld/NinanoModel.xcdatamodel/contents
  Ninano/Ninano/CoreData/ReserveManager.swift
  Ninano/Ninano/Model/HowToUseCoreData.txt
  Ninano/Ninano/Model/SubscriptionModel.swift
  Ninano/Ninano/TEST/APITest/APICaller.swift
  Ninano/Ninano/TEST/APITest/Model.swift
  Ninano/Ninano/TEST/APITest/Test.storyboard
  Ninano/Ninano/TEST/APITest/TestTableViewCell.swift
  Ninano/Ninano/TEST/APITest/TestViewController.swift
  Ninano/Ninano/TEST/CoreDataTest/CoreTestTableViewCell.swift
  Ninano/Ninano/TEST/CoreDataTest/CoredataMain.storyboard
  Ninano/Ninano/TEST/CoreDataTest/CoredataViewController.swift
  Ninano/Ninano/TEST/CoreDataTest/TestTableViewController.swift
Labels: feat

#62 [refactor]: #60 SearchResultView Event Collection UI 변경
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Views/EventTab/SerchResult/PerformancesViewCell.swift
  Ninano/Ninano/Views/EventTab/SerchResult/SearchResult.storyboard
  Ninano/Ninano/extension/Static.swift
Labels: refactor

#67 [feat]: #66 SearchView에서 SearchResultView로 eventData 받기
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Views/EventTab/Search/Search.storyboard
  Ninano/Ninano/Views/EventTab/SerchResult/PerformancesViewCell.swift
  Ninano/Ninano/Views/EventTab/SerchResult/SearchResult.storyboard
Labels: feat

#69 [feat]: #68 SearchResultView에서 EventDetailView로 이동하기
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Views/Base.lproj/EventDetail.storyboard
Labels: feat

#64 [fix] #63 calendarDetailView title 및 back Button 수정
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Controllers/CalendarTab/WeeklyCalendar/CalendarDetailViewController.swift
  Ninano/Ninano/Views/CalendarTab/MonthlyCalendar/Calendar.storyboard
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendar/CalendarDetail.storyboard
  Ninano/Ninano/extension/NavigationItem.swift
Labels: fix

#72 [Feat] #66 SearchResultView로 event 데이터 넘겨주기 위한 모델
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Controllers/CalendarTab/WeeklyCalendar/CalendarDetailViewController.swift
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Model/Event.swift
  Ninano/Ninano/TEST/APITest/APICaller.swift
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendar/CategoryCell.swift
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendar/EventCell.swift
  Ninano/Ninano/Views/EventTab/Search/Search.storyboard
Labels: help wanted

#77 [fix] 알림뷰 (Notice View) UI 수정 및 버그 수정
  Ninano/Ninano/Controllers/CalendarTab/Interest/KeywordViewController.swift
  Ninano/Ninano/Controllers/CalendarTab/Interest/LineSegmentedControl.swift
  Ninano/Ninano/Controllers/CalendarTab/Interest/NoticeViewController.swift
  Ninano/Ninano/Views/CalendarTab/Interest/KeywordTableViewCell.swift
  Ninano/Ninano/Views/CalendarTab/Interest/Notice.storyboard
Labels: fix

#74 [feat]: #73 searchCatagoryView 만들기
  Ninano/Ninano/.swiftLint.yml
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
Labels: feat

#76 [feat]: #75 SearchResultView navigationbar Item UI 반영
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/extension/Static.swift
  Ninano/Ninano/extension/UIImage.swift
Labels: fix

#79 [feat]: #78 searchView와 searchResultView 연결
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Model/Event.swift
  Ninano/Ninano/Views/EventTab/SerchResult/PerformancesViewCell.swift
Labels: feat

#83 [Feat]: #49 공연 추천 뷰 UI 업데이트
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/Views/EventTab/Search/CategoryCell.swift
  Ninano/Ninano/Views/EventTab/Search/EventCell.swift
  Ninano/Ninano/Views/EventTab/Search/Search.storyboard
  Ninano/Ninano/extension/UIFont.swift
Labels: feat

#82 [fix] #81 calendarView & calendarDetailView 배경화면 변경
  Ninano/Ninano/Assets.xcassets/CalendarBackground.imageset/Image.png
  Ninano/Ninano/Assets.xcassets/calendarBackground.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/calendarBackground.imageset/calendarBackground.png
  Ninano/Ninano/Controllers/CalendarTab/WeeklyCalendar/CalendarDetailViewController.swift
  Ninano/Ninano/Views/CalendarTab/MonthlyCalendar/Calendar.storyboard
  Ninano/Ninano/Views/CalendarTab/MonthlyCalendar/CalendarCollectionViewCell.xib
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendar/CalendarDetail.storyboard
Labels: fix

#87 [feat]: #86 구독 버튼 누를 시 키워드가 CoreData에 저장
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Views/EventTab/SerchResult/SearchResult.storyboard
Labels: feat

#97 [fix]: #90 button에 title 값을 바꾸면 button의 fontSize가 달라지는 문제 해결
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Views/EventTab/SerchResult/EventFilterButton.swift
Labels: fix

#98 [fix]: #91 SearchResultView에 systemFont를 적용합니다
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Views/EventTab/SerchResult/EventFilterButton.swift
  Ninano/Ninano/Views/EventTab/SerchResult/EventFilterButton.xib
  Ninano/Ninano/Views/EventTab/SerchResult/PerformancesViewCell.swift
  Ninano/Ninano/Views/EventTab/SerchResult/SearchResult.storyboard
  Ninano/Ninano/extension/customDesign/LabelPadding.swift
Labels: fix

#85 [feat]: #84 PosterDetailView Ui수정 및 기능 구현
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/AppDelegate.swift
  Ninano/Ninano/Controllers/EventDetail/DetailLinkViewController.swift
  Ninano/Ninano/Controllers/EventDetail/EventDetailViewController.swift
  Ninano/Ninano/TEST/APITest/TestTableViewCell.swift
  Ninano/Ninano/Views/Base.lproj/EventDetail.storyboard
Labels: feat, fix

#101 [Feat] #49, #61 공연 추천 View UI, '니나노의 추천공연' 분류
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/Model/Event.swift
  Ninano/Ninano/Views/EventTab/Search/Search.storyboard
Labels: feat

#102 [fix]: calendarDetailView api 받기 및 화면에 표시
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Controllers/CalendarTab/MonthlyCalendar/CalendarViewController.swift
  Ninano/Ninano/Controllers/CalendarTab/WeeklyCalendar/CalendarDetailViewController.swift
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/Model/TempEventModel.swift
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendar/CalendarDetail.storyboard
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendar/DayEventDetailCell.swift
  Ninano/Ninano/extension/StringFormatter.swift
Labels: fix

#106 [Feat]: #104 공연 추천 뷰에서 카테고리 디테일로 넘어가기
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/Views/EventTab/Search/CategoryCell.swift
  Ninano/Ninano/Views/EventTab/Search/Search.storyboard
Labels: feat

#103 [feat] 지역, 날짜, 검색시 collectionView filtering 되기
  Ninano/Ninano/Controllers/CalendarTab/Interest/NoticeViewController.swift
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Model/SubscriptionModel.swift
  Ninano/Ninano/TEST/APITest/TestViewController.swift
  Ninano/Ninano/Views/EventTab/SerchResult/EventFilterButton.swift
  Ninano/Ninano/extension/DateFormatter.swift
Labels: fix

#107 [fix]: #88 사용하지 않는 Asset Image 삭제하기
  Ninano/Ninano/Assets.xcassets/22000743_p.imageset/22000743_p.png
  Ninano/Ninano/Assets.xcassets/22000743_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22005098_p.imageset/22005098_p.png
  Ninano/Ninano/Assets.xcassets/22005098_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22005101_p.imageset/22005101_p.png
  Ninano/Ninano/Assets.xcassets/22005101_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22005605_p.imageset/22005605_p.png
  Ninano/Ninano/Assets.xcassets/22005605_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22006547_p.imageset/22006547_p.png
  Ninano/Ninano/Assets.xcassets/22006547_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22006827_p.imageset/22006827_p.png
  Ninano/Ninano/Assets.xcassets/22006827_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22007535_p.imageset/22007535_p.png
  Ninano/Ninano/Assets.xcassets/22007535_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22007929_p.imageset/22007929_p.png
  Ninano/Ninano/Assets.xcassets/22007929_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22008595_p.imageset/22008595_p.png
  Ninano/Ninano/Assets.xcassets/22008595_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22008615_p.imageset/22008615_p.png
  Ninano/Ninano/Assets.xcassets/22008615_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/22008683_p.imageset/22008683_p.png
  Ninano/Ninano/Assets.xcassets/22008683_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/CalendarDetail/Contents.json
  Ninano/Ninano/Assets.xcassets/CalendarDetail/JulyBG.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/CalendarDetail/JulyBG.imageset/JulyBG.png
  Ninano/Ninano/Assets.xcassets/CalendarDetail/banhyang.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/CalendarDetail/banhyang.imageset/banhyang.png
  Ninano/Ninano/Assets.xcassets/CalendarDetail/guiTo.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/CalendarDetail/guiTo.imageset/guiTo.png
  Ninano/Ninano/Assets.xcassets/JulyBG.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/JulyBG.imageset/Image.png
  Ninano/Ninano/Assets.xcassets/P0003009_p.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/P0003009_p.imageset/P0003009_p.png
  Ninano/Ninano/Assets.xcassets/Poster/Contents.json
  Ninano/Ninano/Assets.xcassets/Search/Contents.json
  Ninano/Ninano/Assets.xcassets/Search/banhyang.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/Search/banhyang.imageset/banhyang.png
  Ninano/Ninano/Assets.xcassets/Search/guiTo.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/Search/guiTo.imageset/guiTo.png
  Ninano/Ninano/Assets.xcassets/Search/heungboga.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/Search/heungboga.imageset/heungboga.png
  Ninano/Ninano/Assets.xcassets/Search/kookakINgayo.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/Search/kookakINgayo.imageset/kookakINgayo.png
  Ninano/Ninano/Assets.xcassets/Search/kyeok.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/Search/kyeok.imageset/kyeok.png
  Ninano/Ninano/Assets.xcassets/Search/satKorMusic.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/Search/satKorMusic.imageset/satKorMusic.png
  Ninano/Ninano/Assets.xcassets/Search/sayooTheater.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/Search/sayooTheater.imageset/sayooTheater.png
  Ninano/Ninano/Assets.xcassets/Search/singerChoonhyang.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/Search/singerChoonhyang.imageset/singerChoonhyang.png
  Ninano/Ninano/Assets.xcassets/Search/stageSejong.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/Search/stageSejong.imageset/stageSejong.png
  Ninano/Ninano/Assets.xcassets/performanceImage1.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/performanceImage1.imageset/performanceImage1.jpeg
  Ninano/Ninano/Assets.xcassets/performanceImage2.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/performanceImage2.imageset/performanceImage2.jpeg
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Model/Event.swift
  Ninano/Ninano/Views/EventTab/SerchResult/PerformancesViewCell.swift
Labels: fix

#109 [fix]: #108 calendar modal title, button 변경하기
  Ninano/Ninano/Views/CalenderModal.storyboard
Labels: fix

#112 [feat] 스켈레톤 이미지, 공연이 없을 때 없다고 표시하기
  Ninano/Ninano/Assets.xcassets/tempPoster.imageset/Contents.json
  Ninano/Ninano/Assets.xcassets/tempPoster.imageset/스크린샷 2022-07-30 오후 7.49.57.png
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Views/EventTab/Search/EventCell.swift
  Ninano/Ninano/Views/EventTab/SerchResult/PerformancesViewCell.swift
  Ninano/Ninano/Views/EventTab/SerchResult/SearchResult.storyboard
  Ninano/Ninano/extension/DateFormatter.swift
Labels: feat

#114 [Feat] #113 "무료 공연" 카테고리 분류
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
Labels: feat

#118 SearchResultView color Hifi랑 동일하게 하기
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Views/EventTab/SerchResult/EventFilterButton.xib
  Ninano/Ninano/Views/EventTab/SerchResult/PerformancesViewCell.swift
  Ninano/Ninano/Views/EventTab/SerchResult/SearchResult.storyboard
  Ninano/Ninano/extension/UIImage.swift
Labels: bug, fix

#119 [feat]: 월달력에 코어데이터와 연결하여 점 표시하기
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Assets.xcassets/tempPoster.imageset/스크린샷 2022-07-30 오후 7.49.57.png
  Ninano/Ninano/Controllers/CalendarTab/MonthlyCalendar/CalendarViewController.swift
  Ninano/Ninano/Controllers/CalendarTab/WeeklyCalendar/CalendarDetailViewController.swift
  Ninano/Ninano/Model/TempEventModel.swift
  Ninano/Ninano/Views/CalendarTab/MonthlyCalendar/CalendarCollectionViewCell.swift
  Ninano/Ninano/Views/CalendarTab/MonthlyCalendar/CalendarCollectionViewCell.xib
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendar/CalendarDetail.storyboard
Labels: feat

#122 [feat] new func in weekly Calendar
  Ninano/Ninano/Controllers/CalendarTab/WeeklyCalendar/CalendarDetailViewController.swift
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/Controllers/EventTab/SearchResult/SearchResultViewController.swift
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendar/CalendarDetail.storyboard
  Ninano/Ninano/Views/EventTab/SerchResult/SearchResult.storyboard
  Ninano/Ninano/extension/DateFormatter.swift
Labels: feat, fix

#123 [Feat]: #115 '이번 달 예정 공연' 카테고리 분류
  Ninano/Ninano.xcodeproj/project.pbxproj
  Ninano/Ninano/Controllers/EventTab/Search/SearchViewController.swift
  Ninano/Ninano/extension/Calendar.swift
Labels: feat

#125 [feat] autolayout 변경, 스켈레톤 이미지 오파시티
  Ninano/Ninano/Controllers/CalendarTab/WeeklyCalendar/CalendarDetailViewController.swift
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendar/CalendarDetail.storyboard
  Ninano/Ninano/Views/CalendarTab/WeeklyCalendar/DayEventDetailCell.swift
  Ninano/Ninano/Views/EventTab/Search/EventCell.swift
Labels: feat, fix
